server:
  port: 8083
  servlet:
    contextPath: /sport-scheduler/v1
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: abenderd
    password: ZL6O87Fw88I
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui